"""Write direct runtime requirements for locally built wheels."""

import sys
from importlib.metadata import PackageNotFoundError, distribution
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


# These are installed from the local wheel artifacts in dist/. Their direct
# dependencies are the only requirements emitted here.
LOCAL_DISTRIBUTIONS = (
    "pytorch-triton",
    "torch",
    "xformers",
    "flash-attn-4",
    "torchvision",
    "torchaudio",
)


def active_requirements(package_name: str) -> list[Requirement]:
    """Return direct, non-optional dependencies for the current interpreter."""
    package = distribution(package_name)
    dependencies = []
    for raw_requirement in package.requires or ():
        requirement = Requirement(raw_requirement)
        if requirement.marker is not None and not requirement.marker.evaluate({"extra": ""}):
            continue
        dependencies.append(requirement)
    return dependencies


def merge_requirement(requirements: dict[str, Requirement], requirement: Requirement) -> None:
    """Combine multiple lower-level requirements for one distribution."""
    canonical_name = canonicalize_name(requirement.name)
    existing = requirements.get(canonical_name)
    if existing is None:
        requirements[canonical_name] = requirement
        return
    if requirement.url or existing.url:
        raise RuntimeError(f"Direct URL runtime requirements are unsupported: {existing}, {requirement}")
    merged_extras = sorted(set(existing.extras) | set(requirement.extras))
    merged_specifier = f"{existing.specifier},{requirement.specifier}".strip(",")
    requirements[canonical_name] = Requirement(
        f"{existing.name}[{','.join(merged_extras)}]{merged_specifier}" if merged_extras else f"{existing.name}{merged_specifier}"
    )


def direct_runtime_requirements() -> dict[str, Requirement]:
    requirements: dict[str, Requirement] = {}
    for package_name in LOCAL_DISTRIBUTIONS:
        try:
            distribution(package_name)
        except PackageNotFoundError as error:
            raise RuntimeError(f"Required local distribution is not installed: {package_name}") from error
        for requirement in active_requirements(package_name):
            merge_requirement(requirements, requirement)

    # The build always installs the CUDA 13 Cutlass extra. Keep only its major
    # version flexible so routine updates can coexist with a target environment.
    try:
        cutlass_version = distribution("nvidia-cutlass-dsl").version
    except PackageNotFoundError as error:
        raise RuntimeError("FA4 CUDA 13 Cutlass runtime is not installed") from error
    cutlass_major = cutlass_version.split(".", maxsplit=1)[0]
    requirements["nvidia-cutlass-dsl"] = Requirement(
        f"nvidia-cutlass-dsl[cu13]>={cutlass_major},<{int(cutlass_major) + 1}"
    )
    return requirements


def main() -> int:
    if len(sys.argv) != 2:
        raise RuntimeError("Usage: write_runtime_requirements.py OUTPUT_PATH")

    output_path = Path(sys.argv[1]).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    runtime_requirements = direct_runtime_requirements()
    output_lines = [
        "# Generated by build.sh from direct Requires-Dist metadata of local wheels.",
        "# Install the matching local wheels from dist/ before this file.",
        "# This list excludes local wheels, test, lint, build-only, and transitive dependencies.",
        "",
    ]
    output_lines.extend(
        str(requirement)
        for _, requirement in sorted(runtime_requirements.items())
    )
    output_path.write_text("\n".join(output_lines) + "\n", encoding="utf-8")
    print(f"Runtime requirements: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
